// Chrome web javascript extension parse-data-v1.js
const FAILED_TO_PARSE = 'FAILED TO PARSE';

const INPUT_FIELD_ID = 'inputData';

const dict = {
    al: "ALL",
    sct: "SET",
    chnce: "SET",
    ech: "EACH",
    ch: "SET",
    st: "SET",
    chance: "SET",
    seat: "SET",
    bored: "BOARD"
};
// replace board ''
const replacements = [
    "3DIGIT",
    "FOUR DIGIT",
    "KERALA 3 PM",
    "KERALA 3",
    "KERALA",
    "PM.3",
    "DR.1",
    "DIAR",
    "DEAR 6PM",
    "DEAR6PM",
    "DEAR6",
    "DEAR 6",
    "DEAR 1 PM",
    "DEAR 1",
    "DEAR1",
    "DEAR-1",
    "DEER",
    "DIAR",
    "PORT",
    //8
    "DEAR 8PM",
    "DEAR1PM",
    "DEAR 1PM",
    "DEAR 1 PM",
    "DEAR8PM",
    "DEAR 8 PM",
    "DEAR-8",
    "DEAR 8",
    "DEAR8",
    "DR.8",
    "1.PM",
    "1 PM",
    "1PM",
    "8PM",
    "6PM",
    "3.PM",
    "3 PM",
    "6.PM",
    "3-00 PM",
    "3.00 PM",
    "3•00 PM",
    "CLOSING",
    "3PM",
    "DEAR",
    "DR 1",
    "DR 6",
    "DR 8",
    "DR 3",
    "DR",
    "KL3",
    "KL.3",
    "KL.6",
    "KL.8",
    "KL.1",
    "KL 8",
    "KL",
    "BOARD",
    "4D",
    "3D",
    "2D",
    "PM",
    "BORED",
    "BORD"
].sort((a, b) => b.length - a.length); 